tt/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index),
    url(r'^tt/', include('ttapp.urls')),
    url(r'^login/$',views.login),
    url(r'^logout/$',views.logout),
    url(r'^register/$',views.register),
]

ttapp/urls.py
from django.conf.urls import url
from . import views

app_name = 'ttapp'
urlpatterns = [
    #ex:/tt/
	url(r'^$', views.IndexView.as_view(), name='index'),
	#ex:/tt/3/
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
     # ex: /polls/5/results/
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
     # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    # crawler
    url(r'^crawler/$', views.crawler_list, name='crawler'),
    url(r'^query/$',views.query_crawler, name ='query'), 
]

ttapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
import datetime
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone

# Create your models here.
@python_2_unicode_compatible 
class Question(models.Model):
    question_text = models.CharField(max_length=190)
    pub_date = models.DateTimeField('date published')
    views = models.IntegerField(default=0)
    
    def __str__(self):
		return self.question_text
		
    def was_published_recently(self):
		return timezone.now()-datetime.timedelta(days=1)<=self.pub_date<=timezone.now()

@python_2_unicode_compatible 
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
    	return self.choice_text


@python_2_unicode_compatible 
class Crawler(models.Model):
    topicID = models.IntegerField(default=0)
    code = models.CharField(max_length=100)
    ctime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.code

tt/views.py
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response,render
from django.views.decorators.csrf import csrf_exempt,csrf_protect 
from django.template.context import RequestContext 
from django.contrib.auth.forms import UserCreationForm



# @csrf_exempt
# @csrf_protect
def login(request):
	if request.user.is_authenticated():
		return HttpResponseRedirect('/tt/')
		#todo change

	username = request.POST.get('username', '')
	password = request.POST.get('password', '')

	user = auth.authenticate(username=username, password=password)

	if user is not None and user.is_active:
		auth.login(request, user)
		return HttpResponseRedirect('/login/')
	else:
		return render(request,'login.html') 



def index(request):
	return render(request,'base.html')

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/tt/')

def register(request):
	if request.method == 'POST':
		print request.POST
		form = UserCreationForm(request.POST)
		if form.is_valid():
			user = form.save()
			return HttpResponseRedirect('/tt/')
	else:
		form = UserCreationForm()
	return render(request,'register.html',locals())

ttapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,get_object_or_404
from django.http import HttpResponseRedirect,HttpResponse,JsonResponse
#from django.urls import reverse
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from django.db.models import Sum,Count

from .models import Question,Choice,Crawler


# Create your views here.
class IndexView(generic.ListView):
    template_name = 'ttapp/index.html'
    model = Question
    # context_object_name = 'new_question_list'

    # def get_queryset(self):
    #     """Return the last five published questions."""
    #     # hot_question_list = Choice.objects.order_by('pub_date')[:5]
    #     return Question.objects.order_by('-pub_datepub_date')[:2]
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['latest_question_list'] = Question.objects.order_by('-pub_date')[:5]
        #select sum(votes) as vote,question_id as qid from ttapp_choice group by question_id order by vote desc;
        #在question上面弄个反向查询，然后再sum，再order_by，再再再取前5个
        #Question.objects.annotate(sumvotes=Sum('choice__votes')).order_by('-sumvotes')
        context['hot_question_list'] = Question.objects.annotate(sumvotes=Sum('choice__votes')).order_by('-sumvotes')[:5]
        return context

def crawler_list(request):
    result = Crawler.objects.filter(ctime__gt='2017-03-28 02:00:46').values('code').annotate(dcount=Count('code')).order_by('-dcount')[:10]
    return render(request, 'ttapp/crawler.html', {'result':result})

def query_crawler(request):
    query_time = request.GET['query_time']
    # query_time = '2017-3-29 00:00:00'
    query_result = Crawler.objects.filter(ctime__gt=query_time).values('code').annotate(dcount=Count('code')).order_by('-dcount')[:10]
    # return JsonResponse({'query_result':list(query_result)})
    return HttpResponse(query_result)

class DetailView(generic.DetailView):
    model = Question
    template_name = 'ttapp/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'ttapp/results.html'
		



def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except(KeyError, Choice.DoesNotExist):
		return render(request, 'ttapp/detail.html',{
			'question':question,
			'error_message':"you didn't select a choice",
		})
	else:
		selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('ttapp:results', args=(question.id,)))

ttapp/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="icon" href="{% static 'ttapp/images/favicon.ico'%}">
    <title>MyDjango</title>
    <!-- <link rel="stylesheet" href="{% static 'style.css' %}"> -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">
    <!-- <link rel="stylesheet" href="{% static 'css/jumbotron-narrow.css' %}"> -->
    <style>
      html,body{ height: 100%;}
      *{ box-sizing:border-box;}
      .imgBox{ transform-style: preserve-3d; position: relative; width:100px; height: 100px; margin:200px auto 0;}
      .imgBox img{width:100%; height: 100%; position: absolute; top:0; transition: transform 1s linear; cursor: pointer;
        border-radius: 10px; box-shadow: 1px 1px 1px 1px #222;}
      @keyframes xzmm{
        from{ transform: perspective(400px) rotateY( 0deg) translateZ(200px);}
        to{ transform: perspective(400px) rotateY( 360deg) translateZ(200px);}
      }
      .imgBox img.sel{ box-shadow: 0 0 3px 1px #00BCD4;}
    </style>
</head>

<body>

    <div class="container">
        <div class="header clearfix">
            <nav>
              <ul class="nav nav-pills pull-right">
                <li role="presentation" class="active">
                    <a href="{% url 'ttapp:index' %}">Home</a>
                </li>
                <li role="presentation"><a href="/tt">Poll</a></li>
                <li role="presentation"><a href="/tt/crawler">Crawler</a></li>
              </ul>
            </nav>
            <h3 class="text-muted">Django Project</h3>
        </div>

        <div class="jumbotron">
            <h1>Jumbotron heading</h1>
            <p class="lead">You keep on concentrating on the things you wish you had or things you wish you didn’t have and you sort of forget what you do have.</p>
            
            {% if request.user.is_authenticated %}
            <p>
                {{request.user}}
                <a class="btn btn-lg btn-success" href="/logout/" role="button">Log Out</a>
            </p>
            {% else %}
                <p><a class="btn btn-lg btn-success" href="/login/" role="button">Log In</a></p>
            {% endif %}
        </div>

        <div class="row marketing">
            <div class="col-lg-6">
              <h4>夏至未至</h4>
              <p>走曾经走过的路，唱曾经唱过的歌，爱曾经爱过的人，却再也提不起恨。</p>

              <h4>时代</h4>
              <p>人的欺骗分为两种：一种是她扭曲了黑白，颠倒了左右。</p>

              <h4>爱与痛的边缘</h4>
              <p>我是个经常笑的人，可是我不是经常快乐，很多时候当我感到悲伤，泪水还没来得及涌上来，笑容已经爬上了眼角眉梢。</p>
            </div>

            <div class="col-lg-6">
              <h4>不再见</h4>
              <p>寂寞的人总是记住生命中出现的每一个人，正如我总是意犹未尽地想起你</p>

              <h4>愿风裁尘</h4>
              <p>很多我们以为一辈子都不会忘记的事情，就在我们念念不忘的日子里，被我们遗忘了。</p>

              <h4>猜火车</h4>
              <p>躲在某一时间，想念某一段时光的掌纹。站在某一地点，想念一个站在来路，也站在一个去路的，让我牵挂的人</p>
            </div>
<!--     <div id="imgBox" class="imgBox">
      <img src="http://p0.so.qhimgs1.com/bdr/_240_/t0172db3b26c0d1d4ac.jpg" />
      <img src="http://p0.so.qhimgs1.com/bdr/_240_/t01435a4eb0bd6efd60.jpg" />
      <img src="http://p1.so.qhimgs1.com/bdr/_240_/t015b7b61b7d7b6957d.jpg" />
      <img src="http://p5.so.qhimgs1.com/bdr/_240_/t017e0d36aa4fbb419b.jpg" />
      <img src="http://p0.so.qhimgs1.com/bdr/_240_/t0187b703add3536f20.jpg" />
      <img src="http://p2.so.qhimgs1.com/bdr/_240_/t0113dc91902322c3ae.jpg" />
      <img src="http://p2.so.qhimgs1.com/bdr/_240_/t01b6aba2da3d0fb5de.jpg" />
      <img src="http://p3.so.qhimgs1.com/bdr/_240_/t01b3b707f7b292d023.jpg" />
      <img src="http://p4.so.qhimgs1.com/bdr/_240_/t01b56d441e69b85004.jpg" />
    </div> -->
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.11.2.js"></script>
    <script>
      $(function(){
        var $imgBox = $("#imgBox");
        var imgCount = $imgBox.children().length;
        var dur = 9;  // 旋转一圈所需时间，单位s
        
        $imgBox.children().each(function(i,dom){
          var $this = $(this);
          $this.css({
            "z-index":  imgCount-i,
            "animation":  "xzmm "+dur+"s linear "+i*(dur/imgCount)+"s infinite forwards"
          }).on("mouseenter",function(){
            $(this).parent().children().removeClass("sel").css({
              "animation-play-state": "paused"
            });
            $(this).addClass("sel");
          }).on("mouseleave",function(){
            $(this).parent().children().removeClass("sel").css({
              "animation-play-state": "running"
            });
          });
        });
      })
    </script>
        

        {% block content %}{% endblock %}

        <footer class="footer">
            <p>Copyright &copy; ZhouHao All rights reserved.</p>
        </footer>    
    </div> <!-- /container -->

</body>
</html>

ttapp/templates/base1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Navbar Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="navbar.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">

      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Project name</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#">About</a></li>
              <li><a href="#">Contact</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li role="separator" class="divider"></li>
                  <li class="dropdown-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="active"><a href="./">Default <span class="sr-only">(current)</span></a></li>
              <li><a href="../navbar-static-top/">Static top</a></li>
              <li><a href="../navbar-fixed-top/">Fixed top</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
        <h1>Navbar example</h1>
        <p>This example is a quick exercise to illustrate how the default, static navbar and fixed to top navbar work. It includes the responsive CSS and HTML, so it also adapts to your viewport and device.</p>
        <p>
          <a class="btn btn-lg btn-primary" href="../../components/#navbar" role="button">View navbar docs &raquo;</a>
        </p>
      </div>

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

ttapp/templates/login.html
<html>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'ttapp/style.css' %}" />
<script type="text/javascript" src="{% static 'ttapp/js/login.js' %}"></script>
    <head>
        <title>Login Page</title>
        <meta charset="utf-8">
    </head>
	<body>
		<form method="post">
		{% csrf_token %}
			<label for="username">用户名称：</label>
			<input type="text" name="username" value="" id="username"><br/>
			<label for="password">用户密码：</label>
			<input type="password" name="password" value="" id="password"><br/>
			<input type="submit" value="登录">
		</form>
		<form>
			<input name="点击我" type="button" value="open" onclick="openPop()"/>
			<input name="点击他" type="button" value="close" onclick="closePop()"/>
		</form>
		


		<div class="test-pop" id="test-pop" style="position:absolute;left:465px;top:267px;z-index:600001;display:none;">
		<form method="post">
		{% csrf_token %}
			<label for="username">用户名称：</label>
			<input type="text" name="username" value="" id="username"><br/>
			<label for="password">用户密码：</label>
			<input type="password" name="password" value="" id="password"><br/>
			<input type="submit" value="登录">
		</form>

	</body>
</html>

ttapp/templates/register.html
<body>
	<h1>注册账号</h1>

	<form action="" method="post">
	{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="注册">

	</form>
		

</body>

ttapp/templates/ttapp/crawler.html
{% extends "base.html" %}
{% load static %}


{% block content %}
	<div class="container-fluid">
		<div class="row-fluid">
			<div class="span2">
				<table class="table table-bordered">
					<thead>
						<tr>
							<th>
								股票编号
							</th>
							<th>
								次數
							</th>	
						</tr>
					</thead>
					<tbody>
					{% for item in result %}
						<tr>
							<td>
								{{ item.code}}
							</td>
							<td>
								{{ item.dcount}}
							</td>
						</tr>
					{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div> 

<div id="query_data">
    <form id = "query_content">
    <div>time：<input type="text" id="query_time">
    <button type="button" id="content_commit">submit</button></div>
    <p>result:<span id='query_result'></span></p>
    </form>
</div>
<script src="http://apps.bdimg.com/libs/jquery/1.11.1/jquery.min.js"></script>
<script>
    $(document).ready(function(){
        $("#content_commit").click(function(){
        	a = $("#query_time").val();
        	$.get("/tt/query/",{'query_time':a},function(ret){
          		$("#query_result").html(ret.encode('UTF-8'));
          		// $.each(ret, function(i, item) {
            // 		$("#query_result").append(
            //         "<div>" + item.id + "</div>" + 
            //         "<div>" + item.code    + "</div>" +
            //         "<div>" + item.dcount + "</div><hr/>");
        // });
        	});
    	});
    });
</script>


{% endblock %}

ttapp/templates/ttapp/detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'ttapp/style.css' %}" />
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


<div class="center">

<form action='{% url 'ttapp:vote' question.id %}' method='post'>
{% csrf_token %}
{% for choice in question.choice_set.all %}
	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" id="vote"/>
</form>
</div>
{% endblock %}

ttapp/templates/ttapp/index.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<!-- <link rel="stylesheet" type="text/css" href="{% static 'ttapp/style.css' %}" />
 --><h1>Welcome, let's begin to poll</h1>


<div class="center">
	{% if latest_question_list %}
<h2>最新投票</h2>
	<ul>
		{% for question in latest_question_list %}
			<li><a href="{% url 'ttapp:detail' question.id %}">{{ question.question_text }}</a></li>
		{% endfor %}
	</ul>
{% else %}
	<p>No tt are available.</p>
{% endif %}

{% if hot_question_list %}
<h2>最热投票</h2>
	<ul>
		{% for question in hot_question_list %}
			<li><a href="{% url 'ttapp:detail' question.id %}">{{ question.question_text }}</a></li>
		{% endfor %}
	</ul>
{% else %}
	<p>No tt are available.</p>
{% endif %}
</div>

{% endblock %}

ttapp/templates/ttapp/results.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'ttapp/style.css' %}" />
<h1>{{ question.question_text }}</h1>


<div class="center">
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a class="vote-again" href="{% url 'ttapp:detail' question.id %}">Vote again?</a>
</div>
{% endblock %}